### ISSUE TITLE
Bad images path

### ISSUE THREAD

**Issue by shaneseaton** [bdunnette/meteor-leaflet-draw#1]
I think after you restructured the css file into the /styles directory, the path to the images in css is 

`http://localhost:3000/packages/bdunnette_leaflet-draw/styles/images/spritesheet.png`

where as the actual location is 

`http://localhost:3000/packages/bdunnette_leaflet-draw/images/spritesheet.png`

I can hack around this with my own css rules, but it would be great if you fixed this, or offered a better solution. 

Thanks,
Shane.

**Comment by bdunnette** [comment]
Thanks for pointing this out @shaneseaton - I've moved the CSS to the package's root directory, which seems to fix the path issue!
